import {
    rightLeg,
    leftLeg,
    rightArm,
    leftArm,
    torso,
    head,
    frame4,
    frame3,
    frame2,
    frame1,
} from './util/drawHangMan.js';
export const state = {
    alphabet: [
        'a',
        'b',
        'c',
        'd',
        'e',
        'f',
        'g',
        'h',
        'i',
        'j',
        'k',
        'l',
        'm',
        'n',
        'o',
        'p',
        'q',
        'r',
        's',
        't',
        'u',
        'v',
        'w',
        'x',
        'y',
        'z',
    ],

    categories: [
        [
            'everton',
            'liverpool',
            'swansea',
            'chelsea',
            'hull',
            'manchester-city',
            'newcastle-united',
        ],
        ['alien', 'dirty-harry', 'gladiator', 'finding-nemo', 'jaws'],
        ['manchester', 'milan', 'madrid', 'amsterdam', 'prague'],
    ],

    hints: [
        [
            'Based in Mersyside',
            'Based in Mersyside',
            'First Welsh team to reach the Premier Leauge',
            'Owned by A russian Billionaire',
            'Once managed by Phil Brown',
            '2013 FA Cup runners up',
            "Gazza's first club",
        ],
        [
            'Science-Fiction horror film',
            '1971 American action film',
            'Historical drama',
            'Anamated Fish',
            'Giant great white shark',
        ],
        [
            'Northern city in the UK',
            'Home of AC and Inter',
            'Spanish capital',
            'Netherlands capital',
            'Czech Republic capital',
        ],
    ],

    guesses: [],
    chosenCategory: null,
    word: null,
    space: 0,
    lives: 10,
    counter: 0,

    drawArray: [
        rightLeg,
        leftLeg,
        rightArm,
        leftArm,
        torso,
        head,
        frame4,
        frame3,
        frame2,
        frame1,
    ],
};
